"""movimentacao

Revision ID: 58b62e2508d3
Revises: c31765b25b9f
Create Date: 2024-04-23 20:44:11.528436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58b62e2508d3'
down_revision = 'c31765b25b9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movimentacao',
    sa.Column('data', sa.Date(), nullable=True),
    sa.Column('nf_id', sa.Integer(), nullable=True),
    sa.Column('produto_id', sa.Integer(), nullable=True),
    sa.Column('estoque_inicial', sa.Integer(), nullable=False),
    sa.Column('qtde_movimentacao', sa.Integer(), nullable=False),
    sa.Column('estoque_final', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=500), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['nf_id'], ['nota_fiscal.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produto.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movimentacao')
    # ### end Alembic commands ###
