"""Estoque Produto

Revision ID: 6b7b304670ba
Revises: fb9f9a85ee98
Create Date: 2024-04-23 19:59:09.539096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b7b304670ba'
down_revision = 'fb9f9a85ee98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
