"""Estoque

Revision ID: fdaf5f3adf35
Revises: fb9f9a85ee98
Create Date: 2024-04-23 20:11:44.789320

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdaf5f3adf35'
down_revision = 'fb9f9a85ee98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.add_column(sa.Column('qtde', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produto', schema=None) as batch_op:
        batch_op.drop_column('qtde')

    # ### end Alembic commands ###
